[package]
name = "job_queue_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
job_queue = { path = "../job_queue" }
tokio = { version = "1.34.0", features = ["full"] }
env_logger = "0.10.1"